### PR TITLE
Avoid conflicting with other FileProviders

### PR DESCRIPTION
**Pull request by rigdern**
If multiple AndroidManifest.xml files specify FileProviders (e.g. the app, a library like react-native-image-picker), you may receive compilation errors when these AndroidManifest.xml files are merged due to conflicts in fields such as `android:authorities` and `android:resource`.

This occurs when multiple AndroidManifest.xml files specify a `android.support.v4.content.FileProvider`. To avoid the conflict, we subclass `android.support.v4.content.FileProvider` and then we refer to our subclass in the AndroidManifest.xml file to avoid the conflict.

This solution is described here: http://stackoverflow.com/a/41550634

I think this might be related to some of the discussion in #485.

Also, I added .vscode/ to .gitignore.

Adam Comella
Microsoft Corp.

### CODE REVIEW

**Comment by jasondibenedetto** [comment]
Upvoting for this to get merged

**Comment by antmespo** [comment]
Seconding

**Comment by bitshadow** [comment]
+1

**Comment by rigdern** [comment]
@haitaoli Can you look into merging this when you get a chance? It's a small low risk PR and a number of people want it (it has [more +1's than any other react-native-image-picker PR](https://github.com/react-community/react-native-image-picker/pulls?q=is%3Apr+is%3Aopen+sort%3Areactions-%2B1-desc)).

Adam Comella
Microsoft Corp.

**Comment by rigdern** [comment]
@haitaoli, thanks for the quick response! 😄

**Comment by paramaggarwal** [comment]
Please release to `npm`. 🙏

**Comment by rigdern** [comment]
@haitaoli Who can publish a version of this library to npm which contains this fix?

Adam Comella
Microsoft Corp.

**Comment by haitaoli** [comment]
@marcshilling can you help push the new version? Thanks.

**Comment by haitaoli** [comment]
@rigdern sorry for the delay. Just published version 0.26.9.

**Pull request merged**
