### PR TITLE
Fix permission issue related to React Native Navigation permanently

### PR DESCRIPTION
**Pull request by DaBs**
## Motivation (required)
Fixes the compatibility issue between React Native Navigation and React Native Image Picker in terms of checking for `PermissionAwareActivity`

## Test Plan (required)

Tests are horribly inadequate and should probably generally be fixed.

### CODE REVIEW

**Comment by haitaoli** [comment]
Can you apply the changes from the other PR into yours?

**Comment by haitaoli** [comment]
I see you already did.

**Comment by haitaoli** [comment]
Published 0.26.10.

**Comment by jholmes033169** [comment]
Is there a schedule for creating a new release?

**Comment by DaBs** [comment]
@jholmes033169 This fix has already reached a release, more specifically 0.26.10

**Comment by cpjolicoeur** [comment]
@DaBs There is no Git tag for `0.26.10`, just FYI.

**Comment by haitaoli** [comment]
@cpjolicoeur just added the tag.

**Comment by cpjolicoeur** [comment]
@haitaoli Thanks.  I also just added #857 to update the `package.json` file to that version as it still was referencing `0.26.7`.

**Comment by DaBs** [comment]
@cpjolicoeur There's a npm version out, which is latest. I don't have permissions to make a git tag.

**Pull request merged**
