### PR TITLE
Fix Compilation Error in React Native 0.47.0

### PR DESCRIPTION
**Pull request by pohodnya**
Thanks for submitting a PR! Please read these instructions carefully:

- [ ] Explain the **motivation** for making this change.
- [ ] Provide a **test plan** demonstrating that the code is solid.
- [ ] Match the **code formatting** of the rest of the codebase.
- [ ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

What existing problem does the pull request solve?

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9

### CODE REVIEW

**Comment by vbuch** [comment]
I'm upvoting for this to get merged

**Comment by deedoc** [comment]
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
They are saying to remove whole method, not just "Override" annotation

**Comment by SanderVerkuil** [comment]
Upvoting too!

Removing the whole method breaks support for earlier versions of react native, so I suggest only removing the annotation.

**Comment by sijad** [comment]
please merge

**Comment by janicduplessis** [comment]
Merged #653. Thanks!

**Pull request closed without merging**
