### PR TITLE
depend on PermissionAwareActivity rather than ReactActivity

### PR DESCRIPTION
**Pull request by hhravn**
Thanks for submitting a PR! Please read these instructions carefully:

## Motivation (required)
react-native-image-picker is incompatible with e.g. wix/react-native-navigation, since NavigationActivity implements PermissionAwareActivity rather than extending ReactActivity. 

## Test Plan (required)
Not really sure.. I guess no further testing should be necessary !?

### CODE REVIEW

**Comment by hhravn** [comment]
duplicates https://github.com/react-community/react-native-image-picker/pull/719

**Comment by aldigjo** [comment]
Any insight on when this can be merged in?

**Comment by paulbargaoanu** [comment]
@brunolemos , @RickiG don't want to put any unnecessary pressure on you guys, but could you possibly give us some info on when to expect this PR to be merged?
Thank you!

**Comment by brunolemos** [comment]
I don't have merge access

**Comment by brunolemos** [comment]
You can use patch-package to apply changes in your project without forking: https://github.com/ds300/patch-package

**Comment by DaBs** [comment]
@haitaoli This is crucial for any React Native Navigation users, which include a good deal of people now a days. Is there a way where we can get this in?

**Comment by haitaoli** [comment]
Does this change break apps that use `ReactActivity` instead of `PermissionAwareActivity`?

**Comment by DaBs** [comment]
Yes, but the fix located at https://github.com/react-community/react-native-image-picker/pull/594/files should not be breaking, as it simply adds another check instead of replacing. We should probably close this one and merge the other?

**Comment by haitaoli** [comment]
Added comments to the other PR. Please close this one.

**Comment by haitaoli** [comment]
Merged: https://github.com/react-community/react-native-image-picker/pull/848

**Pull request closed without merging**
